name:                decimal
version:             0.1.0.0
github:              "natsuki14/decimal"
license:             PublicDomain
author:              "Natsuki Kawai"
maintainer:          "kawai@charon.tech"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/natsuki14/decimal#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- deepseq
- persistent
- scientific
- text

ghc-options:
- -Werror
- -Wno-tabs
- -O2

library:
  source-dirs: src

tests:
  decimal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decimal
